services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    environment:
      NODE_ENV: production

  backend:
    build: 
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: back_end.settings.prod